name: Lint and test

on:
  push:
    branches: [ main ]
  pull_request:    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1

    - name: Build
      run: git submodule update --init --recursive && zig build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1

    - name: Lint
      run: zig fmt --check src/*.zig

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1

    - name: Install cmake
      run: |
        sudo apt update
        sudo apt install -y cmake

    - name: Test
      run: git submodule update --init --recursive && zig build test

  build-aarch64:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Set up Zig
       uses: mlugg/setup-zig@v2
       with:
         version: 0.14.1
    
     - name: Build
       run: git submodule update --init --recursive && zig build -Dtarget="aarch64-linux"
